// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseType int32

const (
	ResponseType_OK    ResponseType = 0
	ResponseType_ERROR ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var ResponseType_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}

func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

type TransactionId struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionId) Reset()         { *m = TransactionId{} }
func (m *TransactionId) String() string { return proto.CompactTextString(m) }
func (*TransactionId) ProtoMessage()    {}
func (*TransactionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *TransactionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionId.Unmarshal(m, b)
}
func (m *TransactionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionId.Marshal(b, m, deterministic)
}
func (m *TransactionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionId.Merge(m, src)
}
func (m *TransactionId) XXX_Size() int {
	return xxx_messageInfo_TransactionId.Size(m)
}
func (m *TransactionId) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionId.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionId proto.InternalMessageInfo

func (m *TransactionId) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Transaction struct {
	Id                   *TransactionId       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId               uint64               `protobuf:"varint,2,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ToId                 uint64               `protobuf:"varint,3,opt,name=toId,proto3" json:"toId,omitempty"`
	ProductId            uint64               `protobuf:"varint,4,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount               uint64               `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() *TransactionId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetFromId() uint64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *Transaction) GetToId() uint64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *Transaction) GetProductId() uint64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Transaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Transactions struct {
	TransactionsList     []*Transaction `protobuf:"bytes,1,rep,name=transactionsList,proto3" json:"transactionsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactionsList() []*Transaction {
	if m != nil {
		return m.TransactionsList
	}
	return nil
}

type Response struct {
	Message              string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 ResponseType `protobuf:"varint,2,opt,name=type,proto3,enum=payment.ResponseType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetType() ResponseType {
	if m != nil {
		return m.Type
	}
	return ResponseType_OK
}

type NoParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParam) Reset()         { *m = NoParam{} }
func (m *NoParam) String() string { return proto.CompactTextString(m) }
func (*NoParam) ProtoMessage()    {}
func (*NoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{4}
}

func (m *NoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParam.Unmarshal(m, b)
}
func (m *NoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParam.Marshal(b, m, deterministic)
}
func (m *NoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParam.Merge(m, src)
}
func (m *NoParam) XXX_Size() int {
	return xxx_messageInfo_NoParam.Size(m)
}
func (m *NoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParam.DiscardUnknown(m)
}

var xxx_messageInfo_NoParam proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("payment.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterType((*TransactionId)(nil), "payment.TransactionId")
	proto.RegisterType((*Transaction)(nil), "payment.Transaction")
	proto.RegisterType((*Transactions)(nil), "payment.Transactions")
	proto.RegisterType((*Response)(nil), "payment.Response")
	proto.RegisterType((*NoParam)(nil), "payment.NoParam")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x86, 0x0d, 0x71, 0x70, 0x19, 0x12, 0x0b, 0x4f, 0x9b, 0x68, 0x85, 0x2a, 0x25, 0xe5, 0x50,
	0xa5, 0x3d, 0x10, 0x89, 0x5e, 0x7a, 0xaa, 0xd2, 0x4a, 0x3d, 0xa0, 0x56, 0x75, 0xb4, 0xf5, 0xa9,
	0xb7, 0x0d, 0x3b, 0x41, 0x48, 0x81, 0x45, 0xec, 0xba, 0x92, 0x9f, 0xa3, 0x4f, 0xd6, 0x37, 0xaa,
	0xb2, 0x18, 0x07, 0x2b, 0x58, 0xea, 0x8d, 0x7f, 0xf6, 0x9f, 0x8f, 0xf9, 0x67, 0x01, 0x4e, 0x1b,
	0xb1, 0xa9, 0xa8, 0x36, 0x49, 0xd3, 0x2a, 0xa3, 0x70, 0xb6, 0x95, 0xd1, 0x45, 0xa1, 0x54, 0xf1,
	0x40, 0xd7, 0xb6, 0x7c, 0xb7, 0xbe, 0xbf, 0x36, 0x65, 0x45, 0xda, 0x88, 0xaa, 0xe9, 0x9c, 0xf1,
	0x05, 0x9c, 0xae, 0x5a, 0x51, 0x6b, 0x91, 0x9b, 0x52, 0xd5, 0x99, 0xc4, 0x39, 0xb8, 0xa5, 0x64,
	0xce, 0xa5, 0x73, 0x35, 0xe5, 0x6e, 0x29, 0xe3, 0xbf, 0x0e, 0x04, 0x03, 0x07, 0xbe, 0xdd, 0x9d,
	0x07, 0xe9, 0x79, 0xd2, 0xbf, 0x76, 0x8f, 0xf1, 0xd8, 0x87, 0xe7, 0xe0, 0xdd, 0xb7, 0xaa, 0xca,
	0x24, 0x73, 0x2d, 0x6b, 0xab, 0x10, 0x61, 0x6a, 0x54, 0x26, 0xd9, 0x91, 0xad, 0xda, 0x67, 0x7c,
	0x0d, 0x7e, 0xd3, 0x2a, 0xb9, 0xce, 0x4d, 0x26, 0xd9, 0xd4, 0x1e, 0x3c, 0x15, 0x1e, 0x49, 0xa2,
	0x52, 0xeb, 0xda, 0xb0, 0xe3, 0x8e, 0xd4, 0x29, 0xfc, 0x08, 0x7e, 0xde, 0x92, 0x30, 0x24, 0x3f,
	0x1b, 0xe6, 0xd9, 0x81, 0xa2, 0xa4, 0xcb, 0x9b, 0xf4, 0x79, 0x93, 0x55, 0x9f, 0x97, 0x3f, 0x99,
	0xe3, 0x5b, 0x38, 0x19, 0x0c, 0xac, 0xf1, 0x06, 0x42, 0x33, 0xd0, 0xdf, 0x4b, 0x6d, 0x98, 0x73,
	0x79, 0x74, 0x15, 0xa4, 0xaf, 0xc6, 0x12, 0xf2, 0x67, 0xee, 0x78, 0x09, 0x2f, 0x38, 0xe9, 0x46,
	0xd5, 0x9a, 0x90, 0xc1, 0xac, 0x22, 0xad, 0x45, 0x41, 0x76, 0x4d, 0x3e, 0xef, 0x25, 0xbe, 0x83,
	0xa9, 0xd9, 0x34, 0x64, 0x37, 0x32, 0x4f, 0xcf, 0x76, 0xec, 0xbe, 0x75, 0xb5, 0x69, 0x88, 0x5b,
	0x4b, 0xec, 0xc3, 0xec, 0x87, 0xba, 0x15, 0xad, 0xa8, 0xde, 0xbf, 0x81, 0x93, 0xa1, 0x01, 0x3d,
	0x70, 0x97, 0xdf, 0xc2, 0x09, 0xfa, 0x70, 0xfc, 0x95, 0xf3, 0x25, 0x0f, 0x9d, 0xf4, 0x8f, 0x0b,
	0x81, 0x51, 0x52, 0xfd, 0xa4, 0xf6, 0x77, 0x99, 0x13, 0x7e, 0x82, 0x45, 0x97, 0x76, 0x78, 0x73,
	0xa3, 0x59, 0xa2, 0xc5, 0xb3, 0x29, 0xe2, 0x09, 0xde, 0xc0, 0x42, 0xd2, 0x03, 0xed, 0xf7, 0x1f,
	0xb8, 0xed, 0x43, 0x84, 0x79, 0x41, 0xe6, 0x7f, 0xda, 0x47, 0xc7, 0xb2, 0x84, 0x97, 0xfb, 0x04,
	0xbb, 0x69, 0x0c, 0x77, 0xf6, 0xed, 0x7e, 0xa2, 0xb3, 0x31, 0x80, 0x8e, 0x27, 0x5f, 0xfc, 0x5f,
	0xfd, 0x7f, 0x70, 0xe7, 0xd9, 0x0f, 0xe2, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xc0,
	0x20, 0xf9, 0x28, 0x03, 0x00, 0x00,
}
