version: "3.3"

services:
  postgres:
    build: "./postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    restart: "always"

  car-listings:
    build: "./car-listings"
    ports: 
      - "4422:4422"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DATABASE: "testdb"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    restart: "always"
    depends_on:
      - postgres
