version: "3.3"

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: "always"

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    restart: "always"

  app:
    build: "./app"
    ports: 
      - "8080:8080"
    environment:
      AMPQ_URL: "amqp://rabbitmq:5672"
      REDIS_ADRESS: "redis"
      REDIS_PORT: "6379"
      REDIS_DATABASE: "0"
      REDIS_PASSWORD: ""
    volumes:
      - myimages:/app/imgs
    restart: "always"
    depends_on:
      - rabbitmq
      - redis
  image-service:
    build: "./image-service"
    ports: 
      - "4322:4322"
    environment:
      AMPQ_URL: "amqp://rabbitmq:5672"
      REDIS_ADRESS: "redis"
      REDIS_PORT: "6379"
      REDIS_DATABASE: "0"
      REDIS_PASSWORD: ""
    volumes:
      - myimages:/app/imgs
    restart: "always"
    depends_on:
      - rabbitmq
      - redis

volumes:
  myimages:
